### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by baconck**
Checking the nested attributes from registration of new members will allow to check if the phone number is ```blank?``` will ensure ```phone_number != ""```. Checking for ```nil?``` will allow ```phone_number == ""```. This might point to why reminders not getting sent. They could have been created with blank phone numbers.

### CODE REVIEW

**Comment by ryanckulp** [comment]
@baconck dude, thanks so much!

but i think we still want the phone number to be optional upon registration, which is why i had the hacky 'allow blank then kill nil number' callback happening.

**Comment by ryanckulp** [comment]
@baconck i'm an idiot, just noticed the proc / reject. testing now.

**Comment by baconck** [comment]
The phone is still optional. The ```reject_if``` just stops the reminder from being created, but not the user.

**Comment by ryanckulp** [comment]
thanks @baconck! great work.

**Pull request merged**
